import icon1 from '../assets/icons/icon (1).png'
import icon2 from '../assets/icons/icon (2).png'
import icon3 from '../assets/icons/icon (3).png'
import icon4 from '../assets/icons/icon (4).png'
import icon5 from '../assets/icons/icon (5).png'
import icon6 from '../assets/icons/icon (6).png'
import icon7 from '../assets/icons/icon (7).png'
import icon8 from '../assets/icons/icon (8).png'
import icon9 from '../assets/icons/icon (9).png'
import icon10 from '../assets/icons/icon (10).png'
import icon11 from '../assets/icons/icon (11).png'
import icon12 from '../assets/icons/icon (12).png'
import icon13 from '../assets/icons/icon (13).png'
import icon14 from '../assets/icons/icon (14).png'
import icon15 from '../assets/icons/icon (15).png'
import icon16 from '../assets/icons/icon (16).png'
import icon17 from '../assets/icons/icon (17).png'
import icon18 from '../assets/icons/icon (18).png'
import icon19 from '../assets/icons/icon (19).png'
import icon20 from '../assets/icons/icon (20).png'
import icon21 from '../assets/icons/icon (21).png'
import icon22 from '../assets/icons/icon (22).png'
import icon23 from '../assets/icons/icon (23).png'
import icon24 from '../assets/icons/icon (24).png'

export const icons ={icon1,icon2,icon3,icon4,icon5,icon6,icon7,icon8,icon9,icon10,icon11,icon12,icon13,icon14,icon15,icon16,icon17,icon18,icon19,icon20,icon21,icon22,icon23,icon24}